# Generated by Django 6.0.5 on 2026-05-18 22:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('concert', 'Concert'), ('entertainment', 'Entertainment'), ('museum', 'Museum'), ('festival', 'Festival'), ('live_show', 'Live Show'), ('sports', 'Sports'), ('theater', 'Theater'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('total_count', models.PositiveIntegerField()),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('max_per_booking', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ticket_types',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('venue', models.CharField(max_length=255)),
                ('venue_address', models.TextField(blank=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='Ethiopia', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold_out', 'Sold Out'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
    ]
